### ISSUE TITLE
Displaying Text

### ISSUE THREAD

**Issue by sebastian-aau** [mgo-tec/ESP32_SSD1331#1]
Hello,

I've been looking into your work. Thank you for your great contributions!

I'm trying to display text on the TTGO T2 v1.2 but I can't find an example of simple text displayed on the OLED. ( board = https://www.aliexpress.com/item/TTGO-T2-ESP32-0-95-OLED-SD-card-WiFi-Bluetooth-Module/32843038592.html?spm=a2g0s.9042311.0.0.27424c4dxU4IXU )

Is it possible for you to provide a simple example of using the library to write a string of text to the OLED?

Thanks a lot...

Best regards,
Sebastian

**Comment by mgo-tec** [comment]
Hello.

Certainly, I did not write my blog post simply displaying letters.

So, I just created my blog post newly.
Please see the link below.

(Japanese)
[https://www.mgo-tec.com/ssd1331-esp32-simple-font-display-spiffs](https://www.mgo-tec.com/ssd1331-esp32-simple-font-display-spiffs)

**Comment by sebastian-aau** [comment]
Thanks a lot for the fast response and for addressing my question. It is just what I'm looking for :)
The Japanese works fine via google-translate and your blog posts are very helpful.

Best regards,
Sebastian
